server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.php index.html;

    # block directory listing
    autoindex off;

    location / {
        try_files $uri $uri/ @rewrite;
    }

    location @rewrite {

        # ANGGOTA
        rewrite ^/anggota$ /modul_anggota/list-anggota.php last;
        rewrite ^/tambah-anggota$ /modul_anggota/tambah-anggota.php last;
        rewrite ^/proses-tambah-anggota$ /modul_anggota/proses-tambah-anggota.php last;
        rewrite ^/edit-anggota/([0-9]+)$ /modul_anggota/edit-anggota.php?anggota_id=$1 last;
        rewrite ^/proses-edit-anggota$ /modul_anggota/proses-edit-anggota.php last;
        rewrite ^/hapus-anggota/([0-9]+)$ /modul_anggota/delete-anggota.php?anggota_id=$1 last;
        rewrite ^/anggota/detail/([0-9]+)$ /modul_anggota/detail.php?id=$1 last;

        # BUKU
        rewrite ^/buku$ /modul_buku/list-buku.php last;
        rewrite ^/tambah-buku$ /modul_buku/tambah-buku.php last;
        rewrite ^/proses-tambah-buku$ /modul_buku/proses-tambah-buku.php last;
        rewrite ^/edit-buku/([0-9]+)$ /modul_buku/edit-buku.php?id_buku=$1 last;
        rewrite ^/proses-edit-buku$ /modul_buku/proses-edit-buku.php last;
        rewrite ^/hapus-buku/([0-9]+)$ /modul_buku/delete-buku.php?id_buku=$1 last;

        # KATEGORI
        rewrite ^/kategori$ /modul_kategori/list-kategori.php last;
        rewrite ^/tambah-kategori$ /modul_kategori/tambah-kategori.php last;
        rewrite ^/proses-tambah-kategori$ /modul_kategori/proses-tambah-kategori.php last;
        rewrite ^/edit-kategori/([0-9]+)$ /modul_kategori/edit-kategori.php?kategori_id=$1 last;
        rewrite ^/proses-edit-kategori$ /modul_kategori/proses-edit-kategori.php last;
        rewrite ^/hapus-kategori/([0-9]+)$ /modul_kategori/proses-delete-kategori.php?kategori_id=$1 last;


        # PEMINJAMAN
        rewrite ^/peminjaman$ /modul_peminjaman/pinjam-data.php last;
        rewrite ^/peminjaman/tambah$ /modul_peminjaman/tambah.php last;

        # PENGEMBALIAN
        rewrite ^/pengembalian$ /modul_pengembalian/list-pengembalian.php last;

        # ROOT
        rewrite ^/login$ /login.php last;
        rewrite ^/logout$ /logout.php last;
        rewrite ^/dashboard$ /home.php last;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}